### ISSUE TITLE
Just Some Ideas

### ISSUE THREAD

**Issue by andrewlalis** [friedelschoen/importsort-d#1]
Hi, just saying that this is something that I've wanted for a long time, and there are a few ideas I've had for a project like this, but I never had time to get the initial version off the ground. Just putting them out there, in case you or I or anyone else might want to take them up:
- Sorting the imports of all .d files in a directory
- Watching file contents to automatically sort if a change occurs.
- If possible, optimizing imports to import only the components used from that module (although this would require some advanced introspection of the code usage and the module, so not really feasible)

**Comment by friedelschoen** [comment]
Thanks for sharing your ideas! I'll look to implement them.

A solution to use this project for now without a watcher: 

- on VSCode I run `importsort-d` on saving with [Run on Save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave)
- on VIM there is a onSave-hook to run this command (so far I know)

**Comment by friedelschoen** [comment]
> Sorting the imports of all .d files in a directory

There is a `--recursive` option implemented!

> Watching file contents to automatically sort if a change occurs.

I've tried to implement it, but it could easily cause some race-contitions and multiple writing, which could currupt  the file.
 
> If possible, optimizing imports to import only the components used from that module (although this would require some advanced introspection of the code usage and the module, so not really feasible)

It's yet a bit out-of-scope, it would be a nice thing to have implemented in a more complex project like a [Language Server](https://github.com/Pure-D/serve-d/).
