### ISSUE TITLE
feature: Do not touch files, if nothing is todo

### ISSUE THREAD

**Issue by gizmomogwai** [friedelschoen/importsort-d#5]

**Comment by friedelschoen** [comment]
Could you please elaborate your issue? I'm not understanding exactly what you mean.

**Comment by gizmomogwai** [comment]
Ah sorry ... e.g. lets say I run the command, but the imports are already in the right sorting order. In this case the filesystem does not need to be touched. Would also make for a nice progressbar (especially with --recursive) .. Like
```
sorting imports for src/main.d -> OK
sorting imports for src/sort.d -> No changes needed
```

**Comment by friedelschoen** [comment]
I implemented your idea 👍🏼 

The problem is, that you have to re-read the file if changes have to made as buffering files could cost a lot of memory.
I'll try to optimalize it a bit and add an option to always sort files.

**Comment by gizmomogwai** [comment]
I see ... I would have just read in the whole file and compared the sorted version with the original one (don't think someone has sourcefiles that big). But if there is another way, it might be better!

Thanks for implementing .. will test now on a few more projects ...

**Comment by gizmomogwai** [comment]
Works nicely, thanks a lot!
